basePath: /
definitions:
  handlers.MetaUrlResponse:
    properties:
      metadata:
        items:
          $ref: '#/definitions/services.ClickMetadata'
        type: array
    type: object
  handlers.inputDelUrl:
    properties:
      url:
        description: URL to delete
        type: string
    type: object
  handlers.inputListUrl:
    properties:
      url:
        type: string
    type: object
  handlers.inputUrl:
    properties:
      url:
        type: string
      user_id:
        type: string
    type: object
  handlers.shortenedUrlResponse:
    properties:
      shortened_url:
        type: string
    type: object
  services.ClickMetadata:
    properties:
      browser:
        type: string
      clicked_at:
        type: string
      device_type:
        type: string
      id:
        type: integer
      ip_address:
        type: string
      operating_system:
        type: string
      referrer:
        type: string
      url_uid:
        type: integer
    type: object
host: zexd.onrender.com
info:
  contact: {}
  description: API for a URL Shortener Service.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  title: ZexD API
  version: "1.0"
paths:
  /{shortenedUrl}:
    get:
      description: Redirects to the original URL from a shortened URL code
      parameters:
      - description: Shortened URL code
        in: path
        name: shortenedUrl
        required: true
        type: string
      responses:
        "302":
          description: Redirects to the original URL
          schema:
            type: string
        "400":
          description: Shortened URL is required
          schema:
            type: string
        "404":
          description: URL not found
          schema:
            type: string
      summary: Redirect to the original URL from a shortened URL
      tags:
      - urls
  /api/create:
    post:
      consumes:
      - application/json
      description: Creates a shortened version of the provided URL
      parameters:
      - description: URL and User ID
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.inputUrl'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.shortenedUrlResponse'
        "400":
          description: Invalid JSON format or missing fields
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Shorten a URL
      tags:
      - urls
  /api/delete:
    post:
      consumes:
      - application/json
      description: Deletes a shortened URL
      parameters:
      - description: URL to delete
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.inputDelUrl'
      produces:
      - application/json
      responses:
        "200":
          description: Success message
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: URL field is required
          schema:
            type: string
        "404":
          description: URL does not exist
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete a shortened URL
      tags:
      - urls
  /api/list/{user_id}:
    get:
      description: Returns a list of URLs for the specified user ID
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of URLs for the user
          schema:
            items:
              type: string
            type: array
        "400":
          description: User ID is required
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List URLs for a specific user ID
      tags:
      - urls
  /api/list/url:
    post:
      consumes:
      - application/json
      description: Returns a list of Metadata for the specified Link
      parameters:
      - description: URL to fetch metadata for
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handlers.inputListUrl'
      produces:
      - application/json
      responses:
        "200":
          description: Metadata for the specified URL
          schema:
            $ref: '#/definitions/handlers.MetaUrlResponse'
        "400":
          description: URL field is required
          schema:
            type: string
        "404":
          description: URL does not exist
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: List Metadata for a specific Link
      tags:
      - urls
  /health:
    get:
      description: Returns a message indicating the server is online
      produces:
      - text/plain
      responses:
        "200":
          description: Server is online
          schema:
            type: string
      summary: Check if the server is online
      tags:
      - health
swagger: "2.0"
